# Generated by Django 4.2.3 on 2023-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0002_vehiculo_propietario_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='parqueadero',
            name='cupo_disponible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parqueadero',
            name='direccion',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
