# Generated by Django 4.2.3 on 2023-07-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0004_remove_parqueadero_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parqueadero',
            name='cupo_disponible',
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='cupo_maximo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parqueadero',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
