# Generated by Django 4.2.3 on 2023-08-01 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0007_remove_parqueadero_cupo_disponible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('propietario', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_eliminacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.parqueadero')),
            ],
        ),
    ]
