# Generated by Django 4.2.3 on 2023-08-01 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0009_delete_vehiculoeliminado'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoEliminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('propietario', models.CharField(max_length=100)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('parqueadero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parqueadero.parqueadero')),
            ],
        ),
    ]
