# Generated by Django 4.2.3 on 2023-07-30 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueadero', '0003_parqueadero_cupo_disponible_parqueadero_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parqueadero',
            name='direccion',
        ),
    ]
